#!/bin/bash
# small-script-repo
# Copyright (C) 2015  Fabian Stiewitz <fabian.stiewitz@protonmail.ch>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo "Usage: small-script-repo (repo (create|remove) | help | version)"
echo "       repo create NAME FOLDER"
echo "            Create new small-script-repo in FOLDER which is accessible via"
echo "            /usr/local/bin/NAME"
echo "       repo remove NAME"
echo "            Remove small-script-repo NAME"
echo "       help"
echo "            Display help"
echo "       version"
echo "            Display version"
